#VS2017 15.9.4 (bump this to force clean vcpkg cache)
version: '{build}'
skip_tags: true
skip_commits:
  files:
    - Change.txt
    - '*.rst'
    - .travis.yml
    - 'docs/*'
    - '.*'
image: Visual Studio 2019
init:
  - ps: if (0) { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) } #rdp debug
install:
  - cmd: echo %time%
  - ps: .\script\install_winsdk.ps1
  - cmd: echo %time%
#  - ps: (Get-Item C:\Qt\5.14\msvc2017_64\bin\Qt5Core.dll).VersionInfo
  # - script\cmd_set.cmd
  # - set

test: off
